### PR TITLE
1st commit

### PR DESCRIPTION
**Pull request by dimitriupe**
not yet finished

### CODE REVIEW

**Comment by dimitriupe** [comment]
Finished the DOM I project!!

**Review by schoell411 — CHANGES_REQUESTED** [review]
--the only thing that needs to be changed, is that you need to 'prepend' one of your new links to the nav bar. you have 'appended' both of them, adding both to the end of the nodeList. Please change one of your links to 'prepend' to the nodeList so that it will move to the front. afterwards i will merge your pull request

**Comment by dimitriupe** [comment]
Requested changes have been made.
Prepend has been used instead of append and now the links are at the front of all nav bar links.
Thank you!

**Review by schoell411 — CHANGES_REQUESTED** [review]
instead of having them both prepend or append, the instructions want you to append one new link, and prepend the other

**Comment by dimitriupe** [comment]
Requested changes made (appendChild() and prepend() ).

**Review by schoell411 — APPROVED** [review]
perfect!

**Pull request merged**
